//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumID { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Icerik { get; set; }
        public Nullable<int> BlogID { get; set; }
        public bool Onay { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
